services:
  flask_app:
    build:
      context: ./flask_app
    ports:
      - "5000:5000"
    env_file:
      - .env

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - flask_app
